---
title: Appendix to "Integrated nested Laplace approximations for extended latent Gaussian models with application to the Naomi HIV model"
subtitle: |
  Corresponding author: Adam Howes (`ath19@ic.ac.uk`)
output:
  pdf_document:
    toc: true
    number_sections: true
    keep_tex: true
    includes:
      in_header: preamble.tex
bibliography: citations.bib
---

\newpage

<!-- So that the tables and figures in this appendix are prefixed by "A." -->
\setcounter{table}{0}  
\renewcommand{\thetable}{A.\arabic{table}} 
\setcounter{figure}{0} 
\renewcommand{\thefigure}{A.\arabic{figure}}

# Modified Naomi model description

## Notation

### Indexing

Consider a given country in sub-Saharan Africa.
Let $x$ refer to a district located within the Spectrum region $R_x$.
We restrict our attention to the time period $t = T_1$ of the most recent national household survey with HIV testing.
Let $s \in \{\text{F}, \text{M}\}$ be sex, and $a \in \{\text{0-5}, \text{5-10}, \ldots, \text{75-80}, 80+\}$ be five-year age bands.
As short-hand, we write $a = l$ to refer to the age band with lower bound $l$, e.g. $a = 20$ for $a = \text{20-25}$.
We index the following quantities by district, sex and age-band: population size $N_{x, s, a}$, HIV prevalence $\rho_{x, s, a}$, ART coverage $\alpha_{x, s, a}$, annual HIV incidence rate $\lambda_{x, s, a}$, and proportion of HIV positive persons recently infected $\kappa_{x, s, a}$.
Sometimes data are observed at an aggregate level, rather than the modelled level of granularity.
In this instance, we use $\{\cdot\}$ to generically refer to a aggregate set over which an observation is made, e.g. $\{a\} = \{\text{15-19}, \ldots, \text{45-49}\}$ for adults.

### Structured random effects

Consider a generic random effect $u$.
We use use structured random effects to share information across units assessed as being similar, such as neighbouring districts or adjacent age-bands.
We use $u \sim \text{ICAR}(\sigma)$ to refer to the Besag intrinsic conditional auto-regressive model (ICAR) [@besag1991bayesian] with full conditionals
$$
u_i \, | \, u_{-i} \sim \mathcal{N} \left(\frac{\sum_{j: j \sim i} u_j}{n_{\delta i}}, \frac{\sigma^2}{n_{\delta i}}\right),
$$
where $u_{-i}$ is $u$ with the $i$th unit removed, $j \sim i$ if the units are defined as adjacent, $n_{\delta i} = |\{j:j \sim i\}|$ is the total number of adjacent units, and $\sigma > 0$ is the marginal standard deviation.
We follow recommendations of @freni2018note on scaling of precision matrices, disconnected adjacency graph components, and islands regarding the ICAR model.
For the reparameterised Besag-York-Mollie model (BYM2) [@simpson2017penalising] we write $u \sim \text{BYM}2(\sigma, \phi)$, where $u$ is comprised of a spatially structured ICAR component $v^\star$ with proportion $\phi \in (0, 1)$ and spatially unstructured IID component $w^\star$ with proportion $1 - \phi$, both scaled to have generalised variance equal to one, and $\sigma > 0$ is the marginal standard deviation such that
$$
u = \sigma \left( \sqrt\phi \cdot v^\star + \sqrt{1 - \phi} \cdot w^\star \right).
$$
We specify the first order auto-regressive model by $u \sim \text{AR}1(\sigma, \phi)$ such that
\begin{align*}
u_1 &\sim \left( 0, \frac{1}{1 - \rho^2} \right), \\
u_i &= \rho u_{i - 1} + \epsilon_t, \quad i = 2, \ldots
\end{align*}
where $\epsilon_i \sim \mathcal{N}(0, 1)$ is Gaussian white noise, $|\rho| < 1$ is the lag-one correlation parameter.

## Process specification

### HIV prevalence

We model HIV prevalence on the logit scale using
$$
\text{logit}(\rho_{x, s, a}) = \beta^\rho_0 + \beta_{S}^{\rho, s = \text{M}} + u^\rho_a + u_a^{\rho, s = \text{M}} + u^\rho_x + u_x^{\rho, s = \text{M}} + u_x^{\rho, a < 15} + \eta^\rho_{R_x, s, a} 
$$
where $\beta^\rho_0$ is an intercept term, $\beta_{s}^{\rho, s = \text{M}}$ is the difference in logit prevalence for men compared to women, $u^\rho_a \sim \text{AR}1(\sigma_A^\rho, \phi_A^\rho)$ are age random effects for women, $u_a^{\rho, s = \text{M}} \sim \text{UNKNOWN}$ are age random effects for the difference in logit prevalence for men compared to women age $a$, $u^\rho_x \sim \text{BYM}2(\sigma_X^\rho, \phi_X^\rho)$ are spatial random effects for women, $u_x^{\rho, s = \text{M}} \sim \text{BYM}2(\sigma_{XS}^\rho, \phi_{XS}^\rho)$ are spatial random effects for the difference in logit prevalence for men compared to women in district $x$, $u_x^{\rho, a < 15} \sim \text{ICAR}(0, \sigma_{XA}^\rho)$ are spatial random effects for the ratio of paediatric prevalence to adult women prevalence, and $\eta^\rho_{R_x, s, a}$ are fixed offsets specifying assumed odds ratios for prevalence outside the age ranges for which data are available.
We use the prior distributions $\mathcal{N}(0, 5)$ for the fixed effects $\beta^\rho_0$ and $\beta_{s}^{\rho, s = \text{M}}$, $\mathcal{N}^{+}(0, 2.5)$ for all standard deviation terms, $\mathcal{U}(-1, 1)$ for all AR1 correlation parameters, and $\text{Beta}(0.5, 0.5)$ for all BYM2 proportion parameters.

### ART coverage

We model ART coverage by
$$
\text{logit}(\alpha_{x, s, a}) = \beta^\alpha_0 + \beta_{S}^{\alpha, s = \text{M}} + u^\alpha_a + u_a^{\alpha, s = \text{M}} + u^\alpha_x + u_x^{\alpha, s = \text{M}} + u_x^{\alpha, a < 15} + \eta^\alpha_{R_x, s, a} 
$$
with terms and priors analogous to the HIV prevalence model above.

### HIV incidence rate

We model HIV incidence rate by
$$
\log(\lambda_{x, s, a}) = \beta_0^\lambda + \beta_S^{\lambda, s = \text{M}} + \log(\rho_{x}^{\text{15-49}}) + \log(1 - \omega \cdot \alpha_{x}^{\text{15-49}}) + u_x^\lambda + \eta_{R_x, s, a}^\lambda 
$$
where $\beta^\lambda_0$ is an intercept term proportional to the average HIV transmission rate for untreated HIV positive adults, $\beta_S^{\lambda, s = \text{M}}$ is the log incidence rate ratio for men compared to women, $\rho_{x}^{\text{15-49}}$ is the HIV prevalence among adults 15-49 calculated by
$$
\rho_{x}^{\text{15-49}} = \frac{\sum_{s \in \{\text{F}, \text{M}\}} \sum_{a = 15}^{45} N_{x, s, a} \cdot \rho_{x, s, a}}{\sum_{s \in \{\text{F}, \text{M}\}} \sum_{a = 15}^{45} N_{x, s, a}},
$$
$\alpha_{x}^{\text{15-49}}$ is the ART coverage among adults 15-49 calculated by
$$
\alpha_{x}^{\text{15-49}} = \frac{\sum_{s \in \{\text{F}, \text{M}\}} \sum_{a = 15}^{45} N_{x, s, a} \cdot \rho_{x, s, a} \cdot \alpha_{x, s, a}}{\sum_{s \in \{\text{F}, \text{M}\}} \sum_{a = 15}^{45} N_{x, s, a} \cdot \rho_{x, s, a}},
$$
$\omega$ is the average reduction in HIV transmission rate per 1% increase in population ART coverage and is fixed at $\omega = 0.7$ via the EPP model, $u_x^\lambda \sim \mathcal{N}(0, \sigma^\lambda)$ with $\sigma^\lambda \sim \mathcal{N}^+(0, 1)$ are IID spatial random effects, and $\eta^\lambda_{R_x, s, a}$ specify log incidence rate ratios by sex and age group calculated from Spectrum model output

### ANC testing

HIV prevalence $\rho_{x, a}^\text{ANC}$ and ART coverage $\alpha_{x, a}^\text{ANC}$ among pregnant women modelled with logit-linear models
\begin{align}
\text{logit}(\rho_{x, a}^{\text{ANC}}) &= \text{logit}(\rho_{x, F, a}) + \beta^{\rho^{\text{ANC}}} + u_x^{\rho^{\text{ANC}}} + \eta_{R_x, a}^{\rho^{\text{ANC}}} \\
\text{logit}(\alpha_{x, a}^{\text{ANC}}) &= \text{logit}(\alpha_{x, F, a}) + \beta^{\alpha^{\text{ANC}}} + u_x^{\alpha^{\text{ANC}}} + \eta_{R_x, a}^{\alpha^{\text{ANC}}},
\end{align}

where $\eta_{R_x, a}^{\theta^{\text{ANC}}}$ for $\theta \in \{\rho, \alpha\}$ are offsets for the log fertility rate ratios for HIV positive women compared to HIV negative women and for women on ART to HIV positive women not on ART, calculated from Spectrum model outputs for region $R_x$, $\beta^{\theta^{\text{ANC}}}$ for $\theta \in \{\rho, \alpha\}$ are the average differences between population and ANC outcomes after removing the offset, and $u_x^{\theta^{\text{ANC}}} \sim \mathcal{N}(0, \sigma_X^{\theta^{\text{ANC}}})$ for $\theta \in \{\rho, \alpha\}$ are district random effects.
  
### ART attendance

Let $\gamma_{x, x'} \in [0, 1]$ be the probability that a person on ART residing in district $x$ recieves ART in district $x'$.
We assume that $\gamma_{x, x'} = 0$ for $x \notin \{x, \text{ne}(x)\}$ such that individuals seek treatment only in their residing district and its neighbours $\text{ne}(x) = \{x': x' \sim x\}$, where $\sim$ is an adjacency relation and $\sum_{x' \in \{x, \text{ne}(x)\}} \gamma_{x, x'} = 1$.

To model $\gamma_{x, x'}$ for $x \sim x'$ we use a multinomial logistic regression model where $\tilde \gamma_{x, x'}$ is the log odds ratio of seeking ART
\begin{align}
\tilde \gamma_{x, x'} &= \tilde \gamma_0 + u_x^{\tilde \gamma} \\ 
\tilde \gamma_0 &= -4 \\
u_x^{\tilde \gamma} &\sim \mathcal{N}(0, \sigma_X^{\tilde \gamma})
\end{align}
where $\tilde \gamma_0$ is an intercept specifying the prior mean for the log odds of seeking ART in each neighbouring district compared to the home district, and $u_x^{\tilde \gamma}$ are district random effects.
We fix $\tilde \gamma_{x, x} = 0$ and recover the multinomial probabilities using the softmax
$$
\gamma_{x, x'} = \frac{\exp(\tilde \gamma_{x, x'})}{\sum_{x^\star \in \{x, \text{ne}(x)\}} \exp(\tilde \gamma_{x, x^\star})}
$$
Then, given the number of PLHIV on ART $A_{x, s, a} = N_{x, s, a} \cdot \rho_{x, s, a} \cdot \alpha_{x, s, a}$, the number of ART clients who reside in district $x$ and obtain ART in district $x'$ are
$$
A_{x, x', s, a} = A_{x, s, a} \cdot \gamma_{x, x'},
$$
and the total attending ART facilities in district $x'$ are
$$
\tilde A_{x', s, a} = \sum_{x \in \{x', \text{ne}(x')\}} A_{x, x', s, a}.
$$

## Likelihood specification

### Household survey data

Let $\nu$ be a household survey occurring at $T_1$, furnishing weighted observations $\hat \theta_{\{x\}, \{s\}, \{a\}, \nu}$ for $\theta \in \{\rho, \alpha, \kappa\}$ with respective Kish effective sample sizes $M^{\hat \theta}_{\{x\}, \{s\}, \{a\}, \nu}$, and observed number of cases
$$
Y^{\hat \theta}_{\{x\}, \{s\}, \{a\}, \nu} = M^{\hat \theta}_{\{x\}, \{s\}, \{a\}, \nu} \cdot \hat \theta_{\{x\}, \{s\}, \{a\}, \nu}.
$$

For HIV prevalence and ART coverage we use binomial working likelihoods as follows
\begin{align}
Y^{\hat \rho}_{\{x\}, \{s\}, \{a\}, \nu} &\sim \text{xBin}(M^{\hat \rho}_{\{x\}, \{s\}, \{a\}, \nu}, \rho_{\{x\}, \{s\}, \{a\}, {T_1}}) \\
\rho_{\{x\}, \{s\}, \{a\}} &= \frac{\sum_{x \in \{x\}} \sum_{s \in \{s\}} \sum_{a \in \{a\}} N_{x, s, a} \cdot \rho_{x, s, a}}{\sum_{x \in \{x\}} \sum_{s \in \{s\}} \sum_{a \in \{a\}} N_{x, s, a}},
\end{align}
and
\begin{align}
Y^{\hat \alpha}_{\{x\}, \{s\}, \{a\}, \nu} &\sim \text{xBin}(M^{\hat \alpha}_{\{x\}, \{s\}, \{a\}, \nu}, \alpha_{\{x\}, \{s\}, \{a\}, {T_1}}) \\
\alpha_{\{x\}, \{s\}, \{a\}} &= \frac{\sum_{x \in \{x\}} \sum_{s \in \{s\}} \sum_{a \in \{a\}} N_{x, s, a} \cdot \rho_{x, s, a} \cdot \alpha_{x, s, a}}{\sum_{x \in \{x\}} \sum_{s \in \{s\}} \sum_{a \in \{a\}} N_{x, s, a} \cdot \rho_{x, s, a}}.
\end{align}

For recent infections we also use a binomial working likelihood
\begin{align}
Y^{\hat \kappa}_{\{x\}, \{s\}, \{a\}, \nu} &\sim \text{xBin}(M^{\hat \kappa}_{\{x\}, \{s\}, \{a\}, \nu}, \kappa_{\{x\}, \{s\}, \{a\}, {T_1}}) \\
\kappa_{x, s, a} &= 1 - \exp(- \lambda_{x, s, a} \cdot \frac{1 - \rho_{x, s, a}}{\rho_{x, s, a}} \cdot (\Omega_T - \beta_T ) - \beta_T ) \\
\Omega_T &\sim \mathcal{N}(\Omega_{T_0}, \sigma^{\Omega_T}) \\
\beta_T &\sim \mathcal{N}(\beta_{T_0}, \sigma^{\beta_T})
\end{align}
where $\kappa_{x, s, a}$ are the predicted proportion recently infected among HIV positive persons, $\Omega_T$ is the mean duration of recent infection (MDRI), and $\beta_T$ is the false recent ratio (FRR).
We use an informative prior on $\Omega_T$ based on the characteristics of the recent infection testing algorithm (RITA).
For PHIA surveys this is $\Omega_{T_0} = 130 \text{ days}$ and $\sigma^{\Omega_T} = 6.12 \text{ days}$.
For PHIA surveys we assume there is no false recency, such that $\beta_{T_0} = 0.0$ and $\sigma^{\beta_T} = 0.0$.

### ANC testing data

For women 15-49 the predicted number of ANC clients $\Psi_{x, a}$ is a log-linear model
$$
\log (\Psi_{x, a}) = \log (N_{x, \text{F}, a}) + \psi_{R_x, a} + \beta^\psi + u_x^\psi
$$
where $N_{x, \text{F}, a}$ are the female population sizes, $\psi_{R_x, a}$ are ASFR in Spectrum region $R_x$ at time $t$, $\beta^\psi$ are the log rate ratio for the number of ANC clients relative to the predicted fertility, $u_x^\psi \sim \mathcal{N}(0, \sigma^\psi)$ are district random effects.

We include ANC testing data for the year of the most recent survey $Y[T_1]$.
Let $W^\text{ANC}_{\{x\}, Y[t]}$ be the number of ANC clients, $X^\text{ANC}_{\{x\}, Y[t]}$ the number of those with ascertained status, $Y^\text{ANC}_{\{x\}, Y[t]}$ the number of those with positive status (either known or tested) and $Z^\text{ANC}_{\{x\}, Y[t]}$ the number of ANC clients already on ART prior to first ANC, such that $W^\text{ANC}_{x, Y[t]} \geq X^\text{ANC}_{x, Y[t]} \geq Y^\text{ANC}_{x, Y[t]} \geq Z^\text{ANC}_{x, Y[t]}$
When ANC testing data are only available for part of a given year, we denote $M^\text{ANC}_{Y[t]} \in \{1, \ldots, 12\}$ the number of months of reported data reflected in counts for year $Y[t]$.

The observed number of HIV positive and already on ART among ANC clients at $Y[T_1]$ is modelled by
\begin{align*}
Y_{\{x\} Y[T_1]}^{\text{ANC}} &\sim \text{Bin} \left(X_{\{x\} Y[T_1]}^{\text{ANC}}, \rho_{\{x\},\{15, \ldots 45\}}^{\text{ANC}}\right) \\
Z_{\{x\} Y[T_1]}^{\text{ANC}} &\sim \text{Bin} \left(Y_{\{x\} Y[T_1]}^{\text{ANC}}, \alpha_{\{x\},\{15, \ldots 45\}}^{\text{ANC}}\right)
\end{align*}
where predicted prevalence and ART coverage are aggregated weighted by the predicted number of pregnant women by age $\Psi_{x, a}$
\begin{align*}
\rho_{\{x\}\{a\}}^{\text{ANC}} &= \frac{\sum_{x \in\{x\}} \sum_{a \in\{a\}} \Psi_{x, a} \cdot \rho_{x, a}^{\text{ANC}}}{\sum_{x \in\{x\}} \sum_{a \in\{a\}} \Psi_{x, a}} \\
\alpha_{\{x\}\{a\}}^{\text{ANC}} &= \frac{\sum_{x \in\{x\}} \sum_{a \in\{a\}} \Psi_{x, a} \cdot \rho_{x, a}^{\text{ANC}} \cdot \alpha_{x, a}^{\text{ANC}}}{\sum_{x \in\{x\}} \sum_{a \in\{a\}} \Psi_{x, a} \cdot \rho_{x, a}^{\text{ANC}}}
\end{align*}

### Number receiving ART

Let $\dot A_{\{x\}, \{s\}, \{a\}}$ be data for the number receiving ART
$$
\dot A_{\{x\}, \{s\}, \{a\}} = \sum_{s \in \{s\}} \sum_{a \in \{a\}} \sum_{x \in \{x\}} \sum_{x \sim x', x = x'} \dot A_{x', x, s, a},
$$
We model the unobserved numbers of ART clients travelling from $x'$ to $x$ as
$$
\dot A_{x', x, s, a} \sim \text{Bin}(N_{x', s, a}, \pi_{x', x, s, a})
$$
where $\pi_{x', x, s, a} = \rho_{x', s, a} \cdot \alpha_{x', s, a} \cdot \gamma_{x', x, s, a}$.
This likelihood is approximated using a normal for the sum of binomials by
$$
\dot A_{\{x\}, \{s\}, \{a\}} \sim \mathcal{N}(\tilde A_{\{x\}, \{s\}, \{a\}}, \sigma^{\tilde A}_{\{x\}, \{s\}, \{a\}})
$$
where
$$
\tilde{A}_{\{x\},\{s\}\{a\}} = \sum_{s \in\{s\}} \sum_{a \in\{a\}} \sum_{x \in\{x\}} \sum_{x \sim x', x = x'} N_{x', s, a} \cdot \pi_{x', x, s, a},
$$
and
$$
\sigma_{\{x\},\{s\}\{a\}}^{\tilde{A}} = \sqrt{\sum_{s \in\{s\}} \sum_{a \in\{a\}} \sum_{x \in\{x\}} \sum_{x \sim x', x = x'} N_{x', s, a} \cdot \pi_{x', x, s, a} \cdot \left(1-\pi_{x', x, s, a}\right)}.
$$

## Identifiability constaints

If data are missing, some parameters are fixed to default values to help with identifiability.
In particular:

* If survey data on ART coverage by age and sex are not available then we set $u_a^\alpha = 0$ and $u_{a, s = \text{M}}^\alpha = 0$ and use the average age/sex pattern of ART coverage from the Spectrum offset $\eta_{R_x, s, a}^\alpha$.
* If no ART data (survey or ART programme) are available at $T_1$ but data on ART coverage among ANC clients are available, the level of ART coverage is not identifiable, but spatial variation is identifiable.
In this instance, overall ART coverage is determined by the Spectrum offset, and only area random effects are estimated
$$
\text{logit} \left(\alpha_{x, s, a} \right) = u_x^\alpha + \eta_{R_x, s, a}^\alpha \\
$$
* If survey data on recent HIV infection are not included in the model, then $\beta_0^\lambda = \beta_S^{\lambda, s = \text{M}} = u_x^\lambda = 0$. The sex ratio for HIV incidence is determined by the sex incidence rate ratio from Spectrum in the same years and the incidence rate in all districts is modelled assuming the same average HIV transmission rate for untreated adults, but varies according to district estimates of HIV prevalence and ART coverage.

\newpage

# MCMC convergence and suitability

We assessed MCMC convergence and suitability using a range of graphical and numerical tests.
These included the potential scale reduction factor $\hat R$, bulk and tail effective sample size (ESS), autocorrelation decay plots, univariate traceplots, pairs density plots, and NUTS specific divergent transition and energy assessments.

For the time being, this analysis is available from `athowes.github.io/elgm-inf/mcmc-convergence`.
Once the MCMC results are finalised, the analysis will be moved to this appendix and expanded upon.
The following draft text and references may be useful in that expanded write-up.

* Improved $\hat R$ statistic from @vehtari2021rank. Recommended only to use the sample if the value is less than 1.05.
* ESS and autocorrelation related to efficiency
* Traceplots helpful for diagnosis of problems
* Pairs density plots helpful for understanding relationships between parameters, including possible indentifiability issues
* Energy plot from @betancourt2017conceptual

\newpage

# \textsc{C++} template

```{cpp, echo=TRUE, eval=FALSE, output.var="ex", code=readLines("naomi_simple.cpp")}

```

\newpage

# References {#references .unnumbered}
