---
title: Integrated nested Laplace approximations for extended latent Gaussian models with application to the Naomi HIV model
author:
  - name: Adam 
    surname: Howes
    email: ath19@ic.ac.uk
    label: e1
    addressLabel: A
    sepNext: ","
  - name: Alex
    surname: Stringer
    email: alex.stringer@uwaterloo.ca
    label: e2
    addressLabel: B
  - name: Seth R.
    surname: Flaxman
    email: seth.flaxman@cs.ox.ac.uk
    label: e3
    addressLabel: C
    sepNext: ","
  - name: Jeffrey W.
    surname: Eaton
    email: jeffrey.eaton@imperial.ac.uk
    label: e4
    addressLabel: D
affiliation:
  - label: A
    name: Department of Mathematics, Imperial College London
    authorsLabels: e1
  - label: B
    name: Department of Statistics and Actuarial Science, University of Waterloo
    authorsLabels: e2
  - label: C
    name: Department of Computer Science, University of Oxford
    authorsLabels: e3
  - label: D
    name: MRC Centre for Global Infectious Disease Analysis, School of Public Health, Imperial College London
    authorsLabels: e4
abstract: |
  | Naomi is a spatial evidence synthesis model used to produce district-level HIV epidemic indicators in sub-Saharan Africa. Multiple outcomes of policy interest, including HIV prevalence, HIV incidence and antiretroviral therapy treatment coverage are jointly modelled using both household survey data and routinely reported health system data. We propose a new inference method which combines the simplified integrated nested Laplace approximation approach of @wood2020simplified with adaptive Gauss-Hermite quadrature to enable fast and accurate inference for Naomi and other extended latent Gaussian models. Using data from Malawi, our method provides substantially more accurate inferences than the empirical Bayes Gaussian approximation approach which is currently in use, and is comparable to Hamiltonian Monte Carlo with the No-U-Turn sampler. By extending the \texttt{aghq} \textsc{R} package we facilitate flexible and easy use of our method when provided a \texttt{TMB} \textsf{C++} template for the model's log-posterior.
keyword-subclass: | 
 \begin{keyword}[class=MSC2020] % It must be define for aap, aop, aos journals. For aoas, sts is not used
 \kwd[Primary ]{00X00}
 \kwd{00X00}
 \kwd[; secondary ]{00X00}
 \end{keyword}
keywords: 
  - spatial statistics
  - small-area estimation
  - INLA
  - AGHQ
  - HIV epidemiology

predefined-theoremstyle: true # use in section Environments for Axiom, Theorem, etc
bibliography: citations.bib
biblio-style: imsart-nameyear # alternative: imsart-number
output:
  rticles::ims_article:
    journal: aoas # aap, aoas, aop, aos, sts. See documentation
    toc: false # Please use for articles with 50 pages and more
    includes:
      in_header: preamble.tex
---

# Introduction

Mounting an effective public health response to the HIV epidemic requires accurate, timely HIV indicator estimates at a sufficiently fine-scale resolution to make targetted interventions.
Producing these estimates is a challenging task beccause all available data sources have shortcomings which must be overcome.
Nationally-representative household surveys provide the most statistically reliable data, but due to their high cost to run, in most countries they occur only infrequently.
Other data sources, such as routine health surveillance of antenatal care clinics, are more real-time but based on limited or biased samples of the population.
To meet these challenges, the Naomi small-area estimation model [@eaton2021naomi] synthesises data from multiple sources to estimate HIV prevalence, HIV incidence, and coverage of antiretroviral treatment (ART) at a district-level.
Simultaneous modelling of the data mitigates the limitations of any single source, increases statistical power, and prompts investigation into any conflicting information.
Software (\url{https://naomi.unaids.org}) has been developed for Naomi, allowing countries to input their data and interactively generate estimates in a yearly process supported by UNAIDS.
The creation of estimates by country teams, rather than external agencies, is a noteworthy feature of the HIV response.
Drawing on expertise closest to the data generating process, improves the accuracy of the process, as well as strengthening trust and ownership of the estimates.

The use case requirements for the model, combined with its relative complexity, present a difficult Bayesian inference problem.
Any inferential strategy must be fast, as well as easy to run in production by country teams, ruling out prohibitively slow Markov chain Monte Carlo (MCMC) approaches.
Inference is currently conducted using an empirical Bayes approach, with a Gaussian approximation to the latent field, via the Template Model Builder (`TMB`) \textsf{R} package [@kristensen2016tmb].
Owing to its speed and flexibility, `TMB` has recently been gaining popularity more broadly in spatial statistics [@osgoodzimmerman2021statistical].
Inference in `TMB` is based on optimisation of a \textsf{C++} template function, with the option available to use a Laplace approximation to integrate out any subset of the function arguments, which for the Naomi model, we use for the high-dimensional latent field parameters.
Taking inspiration from the AD Model Builder (ADMB) package [@fournier2012ad], `TMB` uses automatic differentiation [@baydin2017automatic] to calculate the derivatives required for numerical optimisation routines and the Laplace approximation.
Although this approach has favourable computational properties, we have found the inferences generated for the Naomi model to sometimes be inaccurate.
This has motivated us to look for a more accurate approach, which is flexible enough to be compatible with the model and fast enough to be run in production by country teams.

To obtain fast, accurate inferences for the Naomi model we develop a new inference methodology which combines the simplified integrated nested Laplace approximation (INLA) approach of @wood2020simplified with adaptive Gauss-Hermite quadrature (AGHQ).
INLA is an approach to approximate Bayesian inference based on nested Laplace approximations and numerical quadrature.
The central innovation of @rue2009approximate is an approximation which enables accurate latent field posterior marginals without explicitly computing the full Laplace approximation for each element.
Simplified INLA [@wood2020simplified] extends INLA by relaxing the sparsity assumptions on the latent field required for this approximation to be accurate.
This extension facilitates inference for models like Naomi, which fall within the extended latent Gaussian model (ELGM) [@stringer2022fast] class, and were not previously amenable to inference with INLA.
ELGMs build on latent Gaussian models (LGMs) by allowing each element of the linear predictor to depend on any subset of elements from the latent field.
We combine simplified INLA with AGHQ, a quadrature rule based on the theory of polynomial interpolation which adapts to the integrand based on the Hessian at the mode.
Though no theory yet exists for the nested case, the first stochastic convergence results for adaptive quadrature rules were recently obtained by @bilodeau2021stochastic using AGHQ.
We implement our method as an extension of the `aghq` \textsf{R} package [@stringer2021implementing].
Since `aghq` is designed to naturally interface with `TMB`, use of our method is simple when provided a \textsf{C++} user template for the log-posterior.

The remainder of this paper is organised as follows.
In Section \ref{sec:naomi} we describe a simplified version of the Naomi model that we consider in this paper.
Section \ref{sec:fastinferencemethods} outlines our approach to fast, accurate Bayesian inference using simplified INLA and AGHQ.
As a case-study, we fit the simplified Naomi model on data from Malawi, and compare the accuracy of inferences in Section \ref{sec:naomi}.
We also demonstrate a Bayesian workflow, illustrating the applicability of these tools in a deterministic inference setting.
Finally, in Section \ref{sec:conclusions} we discuss our conclusions, how we anticipate our method might be useful for other models, and directions for future research.

# A simplified Naomi model\label{sec:naomi}

@eaton2021naomi specify a joint model linking small-area estimation models of HIV prevalence from household surveys, HIV prevalence from antenatal care clinics, and antiretroviral therapy (ART) coverage from routine health data collection.
The model is defined over three time points: $T_1$ the time of the most recent household survey with HIV testing; $T_2$, the current time period; and $T_3$, a short term projection period.
We consider a simplified version of the model which is defined only at $T_1$ omitting temporal projection to $T_2$ and $T_3$.
Below we provide an overview of the three components in the simplified model, highlighting the aspects which make it a challenge for existing inferential approaches.
A more complete mathematical description of the simplified model, as well as a \textsf{C++} template for the log-posterior, are provided in the appendix.

## Household survey component

Consider a country in sub-Saharan Africa where a household survey has taken place during the quarter $T_1$.
Let $x$ index district, $a$ five-year age band, $s$ sex and $t$ time.
For ease of notation, let $i$ index the coarsest district-age-sex division included in the model.
The data we observe may be aggregated over indices $i$, so we let $\mathcal{I}$ be a set of $i$ for which observations are reported.
Let $N_i \in \mathbb{N}$ be the population size, $\rho_i \in [0, 1]$ be HIV prevalence, $\alpha_i \in [0, 1]$ be ART coverage, and $\lambda_i > 0$ be the annual HIV incidence rate.
We specify independent mixed effects models for HIV prevalence and ART coverage in the general population on the logit scale such that
\begin{align*}
\text{logit}(\rho_i) &= \eta^\rho_i, \\
\text{logit}(\alpha_i) &= \eta^\alpha_i,
\end{align*}
for certain choice of linear predictors $\eta^\rho_i$ and $\eta^\alpha_i$.
For the HIV incidence rate we use a mixed effects model on the log scale
$$
\log(\lambda_i) = \eta^\lambda_i(\{\rho_i, \alpha_i\}_{i \in \mathcal{I}}),
$$
where the linear predictor depends on $\{\rho_i, \alpha_i\}_{i \in \mathcal{I}}$ for some $\mathcal{I}$.
Let $\kappa_i$ be the proportion recently infected among HIV positive persons.
For each set of observed strata indices $\mathcal{I}$, we calculate the weighted observations $\hat \theta_\mathcal{I}$ for $\theta \in \{\rho, \alpha, \kappa\}$ with respective Kish effective sample sizes 
$$
M^{\hat \theta}_\mathcal{I} = \frac{\left(\sum_j w_j\right)^2}{\sum_j w_j^2},
$$
where $j$ indexes individuals across all strata $i \in \mathcal{I}$, with corresponding survey weights $w_j$.
The observed number of indicator cases is then
$$
Y^{\hat \theta}_{\mathcal{I}} = M^{\hat \theta}_{\mathcal{I}} \cdot \hat \theta_{\mathcal{I}}.
$$
For $\theta \in \{\rho, \alpha, \kappa\}$ we model these aggregate observations using a binomial working likelihood
$$
Y^{\hat \theta}_{\mathcal{I}} \sim \text{xBin}(M^{\hat \theta}_{\mathcal{I}}, \theta_{\mathcal{I}}),
$$
where $\theta_{\mathcal{I}}$ are the following appropriately weighted aggregates
\begin{align*}
\rho_{\mathcal{I}} = \frac{\sum_{i \in \mathcal{I}} N_i \rho_i}{\sum_{i \in \mathcal{I}} N_i}, \\
\alpha_{\mathcal{I}} = \frac{\sum_{i \in \mathcal{I}} N_i \rho_i \alpha_i}{\sum_{i \in \mathcal{I}} N_i \rho_i}, \\
\kappa_{\mathcal{I}} = \frac{\sum_{i \in \mathcal{I}} N_i \rho_i \kappa_i}{\sum_{i \in \mathcal{I}} N_i \rho_i}.
\end{align*}
To link the proportion recently infected among HIV positive persons $\kappa_i$ to HIV incidence $\lambda_i$ we use
$$
\kappa_i = 1- \exp \left( - \lambda \cdot \frac{1 - \rho_i}{\rho_i} \cdot (\Omega_T - \beta_T) - \beta_T \right),
$$
where the mean duration of recent infection $\Omega_T$ and  is the false recent ratio $\beta_T$ are strongly informed by priors for the particular survey.

## ANC testing component

We model HIV prevalence $\rho^\text{ANC}_i$ and ART coverage $\alpha^\text{ANC}_i$ among pregnant women as being offset on the logit scale from the general population indicator as follows
\begin{align*}
\text{logit}(\rho^\text{ANC}_i) &= \text{logit}(\rho_i) + \eta^{\rho^\text{ANC}}_i, \\
\text{logit}(\alpha^\text{ANC}_i) &= \text{logit}(\alpha_i) + \eta^{\rho^\text{ANC}}_i.
\end{align*}
We inform these processes using the following aggregate ANC data from the year of the most recent survey: the number of ANC clients with ascertained status $X^\text{ANC}_\mathcal{I}$, the number of those with positive status $Y^\text{ANC}_\mathcal{I}$, and the number of ANC clients already on ART prior to their first ANC visit $Z^\text{ANC}_\mathcal{I}$.
We use the binomial working likelihoods
\begin{align*}
Y^\text{ANC}_\mathcal{I} &\sim \text{Bin}(Y^\text{ANC}_\mathcal{I}, \alpha^\text{ANC}_{\mathcal{I}}) \\
Z^\text{ANC}_\mathcal{I} &\sim \text{Bin}(Y^\text{ANC}_\mathcal{I}, \alpha^\text{ANC}_{\mathcal{I}}),
\end{align*}
where again we use weighted aggregates
\begin{align*}
\rho^\text{ANC}_{\mathcal{I}} = \frac{\sum_{i \in \mathcal{I}} \Psi_i \rho_i^\text{ANC}}{\sum_{i \in \mathcal{I}} \Psi_i}, \\
\alpha^\text{ANC}_{\mathcal{I}} = \frac{\sum_{i \in \mathcal{I}} \Psi_i \rho^\text{ANC} \alpha^\text{ANC}_i}{\sum_{i \in \mathcal{I}} \Psi_i \rho_i^\text{ANC}},
\end{align*}
with $\Psi_i$ the number of pregnant women.

## ART attendance component

Let $\gamma_{x, x'} \in [0, 1]$ be the probability that a person on ART residing in district $x$ receives ART in district $x'$.
We assume that $\gamma_{x, x'} = 0$ unless $x = x'$ or the two districts are adjacent $x \sim x'$.

Let $\dot A_\mathcal{I}$ be the number of people receiving ART.

# Fast approximate inference methods\label{sec:fastinferencemethods}

Consider a latent Gaussian model (LGM) of the form
\begin{alignat*}{2}
&\text{(Observations)}     &        \y &\sim p(\y \, | \, \x, \btheta), \\
&\text{(Latent field)}     &        \x &\sim \mathcal{N}(\x \, | \, \mathbf{0}, \mathbf{Q}(\btheta)^{-1}), \\
&\text{(Parameters)}       & \qquad \btheta &\sim p(\btheta),
\end{alignat*}
where $\text{dim}(\y) = \text{dim}(\x) = n$ and $\text{dim}(\btheta) = m$, and $m < n$.
The joint posterior of $(\x, \btheta)$ is given by
\begin{equation*}
  p(\x, \btheta \, | \, \y)
  \propto p(\btheta) |\mathbf{Q}(\btheta)|^{n/2} \exp \left( - \frac{1}{2} \x^\top \mathbf{Q}(\btheta) \x + \sum_{i = 1}^n \log p(y_i \, | \, x_i, \btheta) \right).
\end{equation*}
We consider approximations to the posterior marginals of each latent random variable $x_i$ and parameter $\theta_j$ given by
\begin{align}
  \tilde p(x_i \, | \, \y) \approx p(x_i \, | \, \y) &= \int p(x_i, \btheta \, | \, \y) \text{d} \btheta = \int p(x_i \, | \, \btheta, \y) p(\btheta \, | \, \y) \text{d}\btheta, \quad i = 1, \dots, n, \label{eq:inla1} \\
  \tilde p(\theta_j \, | \, \y) \approx p(\theta_j \, | \, \y) &= \int p(\btheta \, | \, \y) \text{d}\btheta_{-j} \quad j = 1, \ldots, m. \label{eq:inla2}
\end{align}

## Algorithm\label{sec:algorithm}

Given a \textsf{C++} user template `model.cpp` for the negative unnormalised log posterior $- \log p(\y, \x, \btheta)$, we obtain the posterior marginal approximations $\{ \tilde p(x_i \, | \, \y) \}_{i = 1}^n$ and $\tilde p(\theta_j \, | \, \y)_{j = 1}^m$ via the following algorithm, comprised of nested applications of Laplace approximation and adaptive Gauss-Hermite quadrature.

<!-- 1. Use a Laplace approximation to obtain the unnormalised $\tilde p_\text{LA}(\btheta, \y)$ -->
<!-- $$ -->
<!-- \tilde p_\text{LA}(\btheta, \y) = \frac{p(\y, \x, \btheta)}{\tilde p_\text{G}(\x \, | \, \btheta, \y)} \Big\rvert_{\x = \hat \x(\btheta)} -->
<!-- $$ -->
<!-- where $\tilde p_\text{G}(\x \, | \, \btheta, \y) = \mathcal{N}(\x \, | \, \hat \x(\btheta), \mathbf{H}(\btheta)^{-1})$ is a Gaussian approximation to $p(\x \, | \, \btheta, \y)$ with mode and precision matrix given by -->
<!-- \begin{align*} -->
<!-- \hat \x(\btheta) &= \argmin_\x - \log p(\y, \x, \btheta), \\ -->
<!-- \mathbf{H}(\btheta) &= \frac{\partial^2}{\partial x \partial x^\top} - \log p(\y, \x, \btheta) \rvert_{\x = \hat \x(\btheta)}. -->
<!-- \end{align*} -->

<!-- 2. Normalise $\tilde p_\text{LA}(\btheta, \y)$ using adaptive Gauss-Hermite quadrature to obtain -->
<!-- $$ -->
<!-- \tilde p_\text{AQ}(\btheta \, | \, \y) = \frac{\tilde p_\text{LA}(\btheta, \y)}{\tilde p_{\text{AQ}}(\y)}, -->
<!-- $$ -->
<!-- where the normalising constant is calculated using nodes from a Gauss-Hermite quadrature rule $\z \in \mathcal{Q}(m, k)$ with $m = \dim(\btheta)$, $k$ nodes per dimension, and weights $\omega: \z \in \mathcal{Q}(m, k) \to \mathbb{R}$ as -->
<!-- $$ -->
<!-- \tilde p_{\text{AQ}}(\y) = \sum_{\z \in \mathcal{Q}(m, k)} \tilde p_\text{LA}(\btheta(\z), \y) \omega(\z). -->
<!-- $$ -->
<!-- The nodes $\z$ are adapted based on the mode and curvature at the mode of the Laplace approximation as follows -->
<!-- \begin{align*} -->
<!-- \btheta(\z) &= \hat{\btheta} + \mathbf{L} \z, \\ -->
<!-- \hat{\btheta} &= \argmax_{\btheta} {\tilde p_\text{LA}(\btheta, \y)}, \\ -->
<!-- \mathbf{H} &= \frac{\partial^2}{\partial \btheta \partial \btheta^\top} - \log \tilde p_\text{LA}(\btheta, \y) \rvert_{\btheta = \hat \btheta} \\ -->
<!-- \mathbf{H}^{-1} &= \mathbf{L} \mathbf{L}^\top. -->
<!-- \end{align*} -->
<!-- We typically set $k = 3$ such that there are $3^m$ nodes in total. -->

<!-- 3. Obtain an unnormalised nested approximation to the posterior marginal of the $i$th latent effect by -->
<!-- $$ -->
<!-- \tilde p_\text{LA}(x_i, \y) = \sum_{\z \in \mathcal{Q}(m, k)} \tilde p_\text{LA}(x_i, \btheta(\z), \y) \omega(\z). -->
<!-- $$ -->
<!-- The nodes and weights $\{\mathcal{Q}(m, k), \omega\}$ used to obtain $\tilde p_{\text{AQ}}(\y)$ are reused to perform integration with respect to the hyperparameters above. -->
<!-- For each of the $k^m$ values of $\btheta(\z)$ we obtain $\tilde p_\text{LA}(x_i, \btheta(\z), \y)$ by setting $\btheta = \btheta(\z)$ in the following Laplace approximation -->
<!-- $$ -->
<!-- \tilde p_\text{LA}(x_i, \btheta, \y) = \frac{p(x_i, \x_{-i}, \btheta, \y)}{\tilde p_\text{G}(\x_{-i} \, | \, x_i, \btheta, \y)} \Big\rvert_{\x_{-i} = \hat \x_{-i}(x_i, \btheta)} -->
<!-- $$ -->
<!-- where $\tilde p_\text{G}(\x \, | \, \btheta, \y) = \mathcal{N}(\x \, | \, \hat \x_{-i}(x_i, \btheta), \mathbf{H}_{-i, -i}(x_i, \btheta)^{-1})$ is a Gaussian approximation to $p(\x \, | \, \btheta, \y)$ with mode and precision matrix given by -->
<!-- \begin{align*} -->
<!-- \hat \x_{-i}(x_i, \btheta) &= \argmin_{\x_{-i}} - \log p(\y, x_i, \x_{-i}, \btheta), \\ -->
<!-- \mathbf{H}_{-i, -i}(x_i, \btheta) &= \frac{\partial^2}{\partial \x_{-i} \partial \x_{-i}^\top} - \log p(\y, x_i, \x_{-i}, \btheta) \rvert_{\x_{-i} = \hat \x_{-i}(x_i, \btheta)}. -->
<!-- \end{align*} -->
<!-- Optimisation to obtain $\hat \x_{-i}(x_i, \btheta)$ may be initialised at $\hat \x(\btheta)_{-i}$. -->


<!-- 4. Normalise $\tilde p_\text{LA}(x_i, \y)$ using $\tilde p_{\text{AQ}}(\y)$ to obtain -->
<!-- $$ -->
<!-- \tilde p_\text{AQ}(x_i \, | \, \y) = \frac{\tilde p_\text{LA}(x_i, \y)}{p_{\text{AQ}}(\y)}. -->
<!-- $$ -->
<!-- which may be evaluated for some choice of values $x_i \in \{\ldots\}$. -->

<!-- The above omiited "forward" algorithm section is written as you would do to calculate things in code. -->
<!-- The "backward" algorithm section to follow is written as you would to have everything defined before it's used. -->

## Algorithm\label{sec:algorithm}

1. Calculate
\begin{align*}
\hat{\btheta} &= \argmax_{\btheta} {\tilde p_\text{LA}(\btheta, \y)}, \\
\mathbf{H} &= \frac{\partial^2}{\partial \btheta \partial \btheta^\top} - \log \tilde p_\text{LA}(\btheta, \y) \rvert_{\btheta = \hat \btheta} \\
\mathbf{H}^{-1} &= \mathbf{L} \mathbf{L}^\top,
\end{align*}
where
$$
\tilde p_\text{LA}(\btheta, \y) = \frac{p(\y, \x, \btheta)}{\tilde p_\text{G}(\x \, | \, \btheta, \y)} \Big\rvert_{\x = \hat \x(\btheta)}
$$
where $\tilde p_\text{G}(\x \, | \, \btheta, \y) = \mathcal{N}(\x \, | \, \hat \x(\btheta), \mathbf{H}(\btheta)^{-1})$ is a Gaussian approximation to $p(\x \, | \, \btheta, \y)$ with mode and precision matrix given by
\begin{align*}
\hat \x(\btheta) &= \argmin_\x - \log p(\y, \x, \btheta), \\
\mathbf{H}(\btheta) &= \frac{\partial^2}{\partial x \partial x^\top} - \log p(\y, \x, \btheta) \rvert_{\x = \hat \x(\btheta)}.
\end{align*}
2. Generate a set of nodes $\z \in \mathcal{Q}(m, k)$ and weights $\omega: \z \in \mathcal{Q}(m, k) \to \mathbb{R}$ from a Gauss-Hermite quadrature rule with $m = \dim(\btheta)$, $k$ nodes per dimension, as follows
\begin{align*}
\btheta(\z) &= \hat{\btheta} + \mathbf{L} \z, \\
\hat{\btheta} &= \argmax_{\btheta} {\tilde p_\text{LA}(\btheta, \y)}, \\
\mathbf{H} &= \frac{\partial^2}{\partial \btheta \partial \btheta^\top} - \log \tilde p_\text{LA}(\btheta, \y) \rvert_{\btheta = \hat \btheta} \\
\mathbf{H}^{-1} &= \mathbf{L} \mathbf{L}^\top.
\end{align*}
We typically set $k = 3$ such that there are $3^m$ nodes in total.
3. Use this quadrature rule to calculate $\tilde p_{\text{AQ}}(\y)$ as follows
$$
\tilde p_{\text{AQ}}(\y) = \sum_{\z \in \mathcal{Q}(m, k)} \tilde p_\text{LA}(\btheta(\z), \y) \omega(\z).
$$
4. For $x_i \in \{\ldots\}$ and $\btheta \in \{ \btheta(\z) \}_{\z \in \mathcal{Q}(m, k)}$ calculate the modes and Hessians
\begin{align*}
\hat \x_{-i}(x_i, \btheta) &= \argmin_{\x_{-i}} - \log p(\y, x_i, \x_{-i}, \btheta), \\
\mathbf{H}_{-i, -i}(x_i, \btheta) &= \frac{\partial^2}{\partial \x_{-i} \partial \x_{-i}^\top} - \log p(\y, x_i, \x_{-i}, \btheta) \rvert_{\x_{-i} = \hat \x_{-i}(x_i, \btheta)},
\end{align*}
where optimisation to obtain $\hat \x_{-i}(x_i, \btheta)$ may be initialised at $\hat \x(\btheta)_{-i}$.

5. For each $x_i$ calculate
$$
\tilde p_\text{AQ}(x_i \, | \, \y) = \frac{\tilde p_\text{LA}(x_i, \y)}{p_{\text{AQ}}(\y)}.
$$
where
$$
\tilde p_\text{LA}(x_i, \y) = \sum_{\z \in \mathcal{Q}(m, k)} \tilde p_\text{LA}(x_i, \btheta(\z), \y) \omega(\z).
$$
and
$$
\tilde p_\text{LA}(x_i, \btheta, \y) = \frac{p(x_i, \x_{-i}, \btheta, \y)}{\tilde p_\text{G}(\x_{-i} \, | \, x_i, \btheta, \y)} \Big\rvert_{\x_{-i} = \hat \x_{-i}(x_i, \btheta)}.
$$

# Application to data from Malawi\label{sec:results}

Using a single `TMB` template, we fit the simplified Naomi model to data from Malawi using four inferential approaches: (1) empirical Bayes combined with a Gaussian approximation, (2) AGHQ combined with a Gaussian approximation, (3) AGHQ combined with a Laplace approximation and (4) the Hamiltonian Monte Carlo (HMC) algorithm No-U-Turn Sampling (NUTS).
The \textsc{R} [@r] code used to produce all results we describe is available at `github.com/athowes/elgm-inf`.

\begin{table}[]
\small
\begin{tabularx}{\textwidth}{lll}
\toprule
 & Run-time & Memory \\
\midrule
Empirical Bayes, Gaussian & 0 & 0 \\
AGHQ, Gaussian & 0 & 0 \\
AGHQ, Laplace & 0 & 0 \\
NUTS & 0 & 0 \\
\bottomrule
\end{tabularx}
\label{tab:results}
\small
\end{table}

## NUTS convergence

In order to treat results from NUTS as the gold-standard we assessed MCMC convergence using.
We ran the algorithm 

## Model assessment

We performed posterior predictive checks to assess the coverage of our estimates via the uniformity of the data within each posterior marginal distribution.

## Inference comparison

We used three methods to assess the accuracy of posterior distributions produced by each inferential method: (1) Kolmogorov-Smirnov tests, (2) maximum mean discrepancy, and (3) Pareto-smoothed importance sampling.

Let $\{\theta_i\}_{i = 1}^n$ be posterior marginal samples with empirical cumulative distribution (ECDF) function $F(\vartheta) = \frac{1}{n} \sum_{i = 1}^n \mathbb{I}_{\theta_i \leq \vartheta}$.
The two-sample Kolmogorov-Smirnov (KS) test statistic is given by the maximum absolute difference between two ECDFs.
We compare the two KS statistics
\begin{align*}
D_\texttt{aghq} &= \sup_\vartheta | F_\texttt{tmbstan}(\vartheta) - F_\texttt{aghq}(\vartheta)|, \\
D_\texttt{TMB} &= \sup_\vartheta | F_\texttt{tmbstan}(\vartheta) - F_\texttt{TMB}(\vartheta)|.
\end{align*}

See results in Table \ref{tab:results}.

\begin{table}[]
\small
\begin{tabularx}{\textwidth}{llll}
\toprule
 & KS & MMD & PSIS \\
\midrule
Empirical Bayes, Gaussian & 0 & 0 & 0 \\
AGHQ, Gaussian & 0 & 0 & 0 \\
AGHQ, Laplace & 0 & 0 & 0 \\
NUTS & 0 & 0 & 0 \\
\bottomrule
\end{tabularx}
\label{tab:results}
\small
\end{table}

# Discussion\label{sec:conclusions}

* We developed an approximate Bayesian inference algorithm to solve a challenging problem in the small-area estimation of HIV in low resource settings
* Following further testing, we anticipate adding our inference method as an option for 
* The flexibility of our method implementation, including compatibility with any `TMB` \textsc{C++} template, allows broader use, as well as investigation of, deterministic inference methods than had previously been possible. We are excited about exploration of its accuracy for the following challenging model structures which could not previously be fit: list of model types here.
* We demonstrated a Bayesian workflow for deterministic inference methods

# Acknowledgements {-}

AH was supported by the EPSRC Centre for Doctoral Training in Modern Statistics and Statistical Machine Learning (EP/S023151/1).
