---
title: "How does increasing $s$ and $k$ effect log normalising constant estimation"
author:
- name: Adam Howes
output:
  bookdown::html_document2:
    toc: yes
    toc_float: yes
    toc_collapsed: yes
    df_print: paged
    code_folding: show
    theme: lumen
abstract: |
  **Background** We have fit the Naomi model with a range of grids.
  
  **Task** How does changing the number of points per dimension $k$, or the number of dimensions of variation kept $s$ change the log normalising constant estimated?
---

# What might be possible?

```{r}
k_seq <- 1:10
s_seq <- 1:10

M <- matrix(0, length(k_seq), length(s_seq))

for (i in 1:length(k_seq)) {
	for (j in 1:length(s_seq)) {
		M[i, j] <- k_seq[i]^(s_seq[j])
  }
}

# Assume anything more than a million isn't possible
M[M > 1e6] <- NA

M
```

# Data import

We start by reading in a selection of fitted PCA-AGHQ models.
We only need certain parts of the fits, and as they are large we are careful here with memory.

```{r}
read_sk <- function(s, k) {
  assign(paste0("s", s, "k", k), readRDS(paste0("depends/aghq-s", s, "-k", k, ".rds"))[c("quad", "time")], envir = parent.frame())
}

read_sk(s = 1, k = 2)
read_sk(s = 2, k = 2)
read_sk(s = 3, k = 2)
read_sk(s = 4, k = 2)
read_sk(s = 5, k = 2)

stopifnot(nrow(s5k2$quad$modesandhessians) == 2^5)

k2 <- list(s1k2, s2k2, s3k2, s4k2, s5k2)
k2_lognormconsts <- sapply(k2, function(x) x$quad$normalized_posterior$lognormconst)
k2_times <- sapply(k2, function(x) x$time)

rm(list = c("k2", "s1k2", "s2k2", "s3k2", "s4k2", "s5k2"))
gc()

read_sk(s = 1, k = 3)
read_sk(s = 2, k = 3)
read_sk(s = 3, k = 3)
read_sk(s = 4, k = 3)
read_sk(s = 5, k = 3)

stopifnot(nrow(s3k3$quad$modesandhessians) == 3^3)

k3 <- list(s1k3, s2k3, s3k3, s4k3, s5k3)
k3_lognormconsts <- sapply(k3, function(x) x$quad$normalized_posterior$lognormconst)
k3_times <- sapply(k3, function(x) x$time)

rm(list = c("k3", "s1k3", "s2k3", "s3k3", "s4k3", "s5k3"))
gc()

read_sk(s = 1, k = 5)
read_sk(s = 2, k = 5)
read_sk(s = 3, k = 5)
read_sk(s = 4, k = 5)
read_sk(s = 5, k = 5)

k5 <- list(s1k5, s2k5, s3k5, s4k5, s5k5)
k5_lognormconsts <- sapply(k5, function(x) x$quad$normalized_posterior$lognormconst)
k5_times <- sapply(k5, function(x) x$time)

rm(list = c("k5", "s1k5", "s2k5", "s3k5", "s4k5", "s5k5"))
gc()
```

# Table processing

```{r}
df <- data.frame(
  s = rep(1:5, times = 3),
  k = rep(c(2, 3, 5), each = 5),
  lognormconst = c(k2_lognormconsts, k3_lognormconsts, k5_lognormconsts),
  time = c(k2_times, k3_times, k5_times),
)

write_csv(df, "increase-s-k.csv")
```

# Visualisation

```{r}
ggplot(df, aes(x = s, y = lognormconst)) +
  geom_point() +
  facet_grid(. ~ k) +
  labs(x = "Dimensions kept of the PCA", y = "Log normalising constant") +
  theme_minimal()
```


```{r}
ggplot(df, aes(x = s, y = time)) +
  geom_point() +
  facet_grid(. ~ k) +
  scale_y_continuous(limits = c(0, NA)) +
  labs(x = "Dimensions kept of the PCA", y = "Time (mins)") +
  theme_minimal()
```
