---
title: Explaining approximate deterministic inference methods
subtitle: HIV Inference Lab Group Meeting
author: Adam Howes
institute: Imperial College London
date: December 2022
bibliography: citations.bib
output:
  beamer_presentation:
    latex_engine: pdflatex
    highlight: haddock
    fig_width: 7 
    fig_height: 3
    includes:
        in_header: preamble.tex
---

# Bayes

* As a statistical modeller, our whole job (approximately) is to construct a generative model for data $y$ using parameters $\vartheta$
* This is the joint distribution $p(y, \vartheta) = p(y \, | \, \vartheta) p(\vartheta)$
* What we actually want is the posterior $p(\vartheta \, | \, y)$ which is **just**^[I've bolded this for sarcasm.]
$$
p(\vartheta \, | \, y) = \frac{p(y, \vartheta)}{p(y)} = \frac{p(y \, | \, \vartheta) p(\vartheta)}{p(y)}
$$
* The **core problem** of Bayesian inference is that we can't compute $p(y)$
$$
p(y) = \int p(y, \vartheta) \text{d} \vartheta
$$

# How might you do it?

* Usually if you wanted to integrate something, you could use numerical integration methods
* Pick nodes $\vartheta_i$ and weights $\omega_i$ then compute the sum
$$
\tilde p(y) = \sum_i p(y, \vartheta_i) \omega_i
$$

# Monte Carlo as an example of numerical integration

* Suppose we can sample $\vartheta_i \sim p(y, \vartheta)$ for $i = 1, \ldots, N$
* If we set $\omega_i = 1/N$ for all $i$ then
$$
\tilde p(y) = \frac{1}{N} \sum_i p(y, \vartheta_i)
$$

# Monte Carlo is fundamentally unsound

* "Monte Carlo ignores information" according to @o1987monte
* Suppose $N = 3$ and we sample $\vartheta_1, \vartheta_2, \vartheta_3$ with $\vartheta_2 = \vartheta_3$ then our MC estimate is
$$
\tilde p(y) = \frac{1}{3} \left( p(y, \vartheta_1) + p(y, \vartheta_2) + p(y, \vartheta_3) \right)
$$
* This is despite the fact that nothing new about the function has been learned by adding $\{\vartheta_3, p(y, \vartheta_3)\}$

# Application to HIV survey sampling

* Suppose we're running a household survey, and sample the same individual twice
* We didn't learn anything new about HIV by surveying them again!
* This doesn't just bite for nodes or individuals which are exactly the same: an analogous argument can be made if they are close together and we expect their function evaluations to be similar

\begin{center}
\begin{tcolorbox}[width=0.9\textwidth, colframe={title}, colback={white}, title={}]
$\implies$ Bayesian quadrature, Bayesian survey design (end of digression)
\end{tcolorbox}
\end{center}

# Latent variables and hyperparameters

* Quadrature doesn't work very well when $\text{dim}(\vartheta)$ gets even moderately sized
* Previously I had all of the parameters under the symbol $\vartheta$
* What if we split them up as being $\vartheta = (x, \theta)$
* The key part about this is that $\dim(x)$ is big and $\dim(\theta)$ is small

| Names for $x$ | Names for $\theta$ |
|---------------|--------------------|
| Latent variables, random effects, latent field | Hyperparameters, fixed effects 

# Spatio-temporal statistics

* There is nothing inherently special about spatio-temporal statistics
* We have observations indexed by space $s \in \mathcal{S}$ and time $t \in \mathcal{T}$
* Usually we associate parameters to spatio-temporal locations as well as observations
* This ends up with us having something like $\{x_{s, t}\}$

# What's important about this?

1. There might be **a lot** of spatio-temporal locations, so $\text{dim}(x)$ might be pretty big!
 * If you have 100 districts and 10 years, that's already $100 \times 10 = 1000$ parameters
2. Perhaps we're willing to make assumptions about how things vary over space-time

<!-- As you get more data, the posterior approaches a Gaussian -->

# Latent Gaussian models

\begin{alignat*}{2}
  &\text{(Observations)}     &   y &\sim p(y \, | \, x, \theta), \\
  &\text{(Latent field)}     &   x &\sim \mathcal{N}(x  \, | \, \mu(\theta), Q(\theta)^{-1}), \\
  &\text{(Hyperparameters)}  &   \qquad \theta &\sim p(\theta),
\end{alignat*}
where $y = (y_1, \ldots, y_n)$, $x = (x_1, \ldots, x_n)$, $\theta = (\theta_1, \ldots, \theta_m)$

# References {.allowframebreaks}
