---
poster_height: "46.8in"
poster_width: "33.1in"
font_family: "Open Sans"
# Essentials
title: Fast approximate Bayesian inference for small-area estimation of HIV indicators using the Naomi model
author:
  - name: "Adam Howes"
    affil: 1, 2
    main: true
    twitter: adamhowes
    email: ath19@ic.ac.uk
  - name: "Alex Stringer"
    affil: 3
  - name: "Seth R. Flaxman"
    affil: 4
  - name: "Jeffrey W. Eaton"
    affil: 2
affiliation:
  - num: 1
    address: Department of Mathematics, Imperial College London
  - num: 2
    address: MRC Centre for Global Infectious Disease Analysis, School of Public Health, Imperial College London
  - num: 3
    address: Department of Statistics and Actuarial Science, University of Waterloo
  - num: 4
    address: Department of Computer Science, University of Oxford
logoleft_name: "IMP_ML_W_N.png"
logoright_name: "UW_ML_W_N.png"
# Style & formatting
column_numbers: 3
title_textsize: "75px"
author_textsize: "45px"
authorextra_textsize: "35px"
affiliation_textsize: "25px"
caption_fontsize: "20px"
# Title box
title_textcol: "#ffffff"
author_textcol: "#ffffff"
affiliation_textcol: "#ffffff"
# Main
main_fontfamily: "Open Sans"
# Poster body options
primary_colour: "#009E73"
secondary_colour: "#3b77D8"
accent_colour: "#5d19c4"
body_bgcol: "#ffffff"
body_textsize: "35px"
body_textcol: "#000000"
reference_textsize: "25px"
sectitle_textsize: "40px"
# Standard options
bibliography: citations.bib
output: 
  posterdown::posterdown_html:
    self_contained: false
    pandoc_args: --mathjax
    highlight: espresso
    number_sections: false
---

## Summary

* Approximate Bayesian inference method combining Laplace approximations and adaptive Gauss-Hermite quadrature 
* Motivated by a challenging, policy-relevant problem in small-area estimation of HIV indicators in sub-Saharan Africa
* Implemented as a part of the `aghq` R package, allowing use for any model with a `TMB` C++ user template

<!-- 38761C -->

## The Naomi HIV model

* District-level model of HIV indicators which synthesises data from household surveys, antenatal care (ANC) clincs, and routine service provision of antiretroviral therapy (ART) [@eaton2021naomi]
* Yearly estimation process: model run interactively by country teams using the web-app `naomi.unaids.org`
* Inference currently conducted with empirical Bayes and a Gaussian approximation to the latent field using Template Model Builder `TMB` [@kristensen2016tmb]
* Days to get accurate answers with Markov chain Monte Carlo via `tmbstan` [@monnahan2018no]
* Motivates looking for a fast, approximate approach

## Extended latent Gaussian models

* In a latent Gaussian model (LGM) [@rue2009approximate] the conditional mean depends on exactly one structured additive predictor $\mu_i = g(\eta_i)$ with $g: \mathbb{R} \to \mathbb{R}$
  * The `R-INLA` implementation of integrated nested Laplace approximations applies only to LGMs
* Extended latent Gaussian models (ELGM) remove this requirement such that $\mu_i = g(\eta_{\mathcal{J_i}})$ where $g_i: \mathbb{R}^{|\mathcal{J_i}|} \to \mathbb{R}$
* Naomi is an ELGM, and not an LGM, because in our model:
  * ANC indicators are offset from household survey indicators
  * Incidence depends on prevalence and ART coverage
  * Observed data may be aggregated
  * Individuals may attend ART clinics outside their home district

## Inference procedure

### Background

* **Laplace approximation** Integrate out variables using a Gaussian approximation to the denominator e.g.
$$
p(\theta, y) \approx \tilde p_\text{LA}(\theta, y) = \frac{p(y, x, \theta)}{\tilde p_\text{G}(x \, | \, \theta, y)} \Big\rvert_{x = \hat x(\theta)}
$$
where $\tilde p_\text{G}(x \, | \, \theta, y) = \mathcal{N}(x \, | \, \hat x(\theta), \mathbf{H}(\theta)^{-1})$
* **Adaptive Gauss-Hermite Quadrature** Approximate integrals by $\int_\Theta p(\theta) \text{d} \theta \approx \lvert L \rvert \sum_{z \in \mathcal{Q}(m, k)} p(\hat \theta + Lz) \omega(z)$ with Gauss-Hermite quadrature rule $z \in \mathcal{Q}(m, k)$ adapted based upon the mode $\hat \theta = \text{argmax}_{\theta \in \Theta} \in p(\theta)$ and lower Cholesky $LL^\top = - \partial_\theta^2 \log p(\theta) \rvert_{\theta = \hat \theta}$ of the target

### Our algorithm

* Given a C++ user template for $- \log p(y, x, \theta)$ our algorithm is summarized by Figure 1

```{tikz, tikz-ex, echo=FALSE, fig.align='center', fig.cap = "Flowchart describing the algorithm", fig.ext = 'png', cache=TRUE}
\usetikzlibrary{arrows}
\begin{tikzpicture}[node distance=4cm, auto,>=latex', thick, scale = 1]
\node (1) {$p(\theta, x, y)$};
\node (2) [right of=1] {$\tilde p_\text{LA}(\theta, y)$};
\node (3) [below of=1] {$\tilde p_\text{LA}(x_i, \theta, y)$};
\node (4) [below of=2] {$\tilde p_\text{AQ}(y)$};
\draw[->] (1) to node {Laplace} (2);
\end{tikzpicture}
```

## Inference comparison

* Compare posterior inferences from `TMB`, `aghq`, `adam` and `tmbstan` using Kolmogorov-Smirnov tests on posterior marginals of hyperparameters, latent field, and outputs
* Figure 2 compares the distances between `TMB` and `adam` to `tmbstan`

## Future work

* More comprehensive inference comparison e.g. maximum mean discrepancy, Pareto-smoothed importance sampling
* Implement Laplace matrix algebra approximations e.g. @wood2020simplified

<font size="6"> **Interested to read more?** Working notebooks and R code available are available from `github.com/athowes/multi-agyw`. </font>

<font size="6"> **Funding** AH was supported by the EPSRC and Bill & Melinda Gates Foundation. This research was supported by the MRC Centre for Global Infectious Disease Analysis. </font>

## References

<font size="5"> <div id="refs" class="references"></div> </font>
