---
title: "Inference methods comparison for the simplified Naomi model using maximum mean discrepancy"
author:
- name: Adam Howes
output:
  bookdown::html_document2:
    toc: yes
    toc_float: yes
    toc_collapsed: yes
    df_print: paged
    code_folding: show
    theme: lumen
abstract: |
  **Background**  We have run the simplified Naomi model using a range of inference methods: `TMB`, `aghq` and `tmbstan`.
  
  **Task** In this report, we compare the accuracy of the posterior distributions obtained from these inference methods using maximum mean discrepancy.
---

# Background

We compare the inference results from `TMB`, `aghq`, `adam`, and `tmbstan`.
Import these inference results as follows:

```{r}
tmb <- readRDS("depends/tmb.rds")
aghq <- readRDS("depends/aghq.rds")
tmbstan <- readRDS("depends/tmbstan.rds")
```

Check that the parameters (latent field, hyperparameters, model outputs) sampled from each of the four methods are the same:

```{r}
stopifnot(names(tmb$fit$sample) == names(aghq$quad$sample))
stopifnot(setequal(names(tmb$fit$sample), names(tmbstan$mcmc$sample)))
```

# Maximum mean discrepancy

```{r}
par_samp_matrix <- function(sample) {
  x <- sample[!(stringr::str_ends(names(sample), "_out") | stringr::str_ends(names(sample), "_ll"))]
  do.call(rbind, x)
}

tmb_samples <- par_samp_matrix(tmb$fit$sample)
aghq_samples <- par_samp_matrix(aghq$quad$sample)
tmbstan_samples <- par_samp_matrix(tmbstan$mcmc$sample)

#' Thin down to 1000 samples from tmbstan
tmbstan_samples <- tmbstan_samples[, seq(from = 1, to = ncol(tmbstan_samples), length.out = 1000)]

mmd_tmb <- kernlab::kmmd(tmb_samples, tmbstan_samples, kernel = "rbfdot")
mmd_aghq <- kernlab::kmmd(aghq_samples, tmbstan_samples, kernel = "rbfdot")

#' Take sigma to be the mean estimated for the two different methods
kpar <- list(sigma = mean(mmd_tmb@kernelf@kpar$sigma, mmd_aghq@kernelf@kpar$sigma))

#' Rerun with sigma the same across the different tests
mmd_tmb <- kernlab::kmmd(tmb_samples, tmbstan_samples, kernel = "rbfdot", kpar = kpar, alpha = 0.05)
mmd_aghq <- kernlab::kmmd(aghq_samples, tmbstan_samples, kernel = "rbfdot", kpar = kpar, alpha = 0.05)

mmd_tmb
mmd_aghq

mmd_tmb@mmdstats
mmd_aghq@mmdstats

round(100 * (mmd_aghq@mmdstats[1] - mmd_tmb@mmdstats[1]) / mmd_tmb@mmdstats[1])
round(100 * (mmd_aghq@mmdstats[2] - mmd_tmb@mmdstats[2]) / mmd_tmb@mmdstats[2])

saveRDS(list(mmd_tmb = mmd_tmb, mmd_aghq = mmd_aghq), file = "mmd.rds")
```
