---
title: "BayesComp 2023 and Bayesian Inference of Epidemics abstract submission"
author: "Adam Howes, Imperial College London"
date: "29th September 2022"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

[BayesComp 2023](https://bayescomp2023.com/) and [Bayesian Inference of Epidemics](https://warwick.ac.uk/fac/sci/statistics/staff/academic-research/corbella/bcepidemics2023).

```{r echo=FALSE}
title <- "Integrated nested Laplace approximations for extended latent Gaussian models, with application to the Naomi HIV model"
abstract <- "Naomi (Eaton et al, 2021) is a spatial evidence synthesis model used to produce district-level HIV epidemic indicators in sub-Saharan Africa. Multiple outcomes of interest, including HIV prevalence, HIV incidence and treatment coverage are jointly modelled using both household survey data and routinely reported health system data. The model is provided as a tool for countries to input their data to and generate estimates. In this setting, computationally intensive inference methods like MCMC are impractical. We propose a new inference method which combines the simplified integrated nested Laplace approximation approach of Wood (2020) with adaptive Gauss-Hermite quadrature to enable fast and accurate inference for Naomi and other extended latent Gaussian models. Using data from Malawi, we show that the inferences obtained by our method are substantially more accurate than the empirical Bayes Gaussian approximation approach used currently, as compared with inferences from HMC with the No-U-Turn sampler as a gold-standard, where all methods are implemented via a common `TMB` C++ template for the log-posterior. By extending the `aghq` package (Stringer, 2021) we facilitate flexible and easy use of our method when provided a `TMB` template."
```

**Title**:
```{r echo=FALSE, results='asis'}
cat(title)
```

Title word count: `r stringr::str_count(title, '\\w+')`.

**Abstract**:
```{r echo=FALSE, results='asis'}
cat(abstract)
```

Abstract word count: `r stringr::str_count(abstract, '\\w+')`/200.
