---
title: "Waterloo seminar series abstract"
author: "Adam Howes, Imperial College London"
date: "15th November 2022"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r echo=FALSE}
title <- "Integrated nested Laplace approximations for extended latent Gaussian models with application to the Naomi HIV model"
abstract <- "Naomi (Eaton et al, 2021) is a spatial evidence synthesis model used to produce district-level HIV epidemic indicators in sub-Saharan Africa. Multiple outcomes of interest, including HIV prevalence, HIV incidence and treatment coverage are jointly modelled using both household survey data and routinely reported health system data. The model is provided as a tool for countries to input their data to and generate estimates (see https://naomi.unaids.org/). In this setting, computationally intensive inference methods like MCMC are impractical. To enable fast and accurate inference for Naomi, and other extended latent Gaussian models, we are developing a new inference method which combines the simplified integrated nested Laplace approximation approach of Wood (2020) with adaptive Gauss-Hermite quadrature. The new method will be implemented as an extension of the `aghq` package (Stringer, 2021), which will facilitate flexible and particularly easy use when provided a `TMB` C++ template for the log-posterior. In this talk, I'll discuss this progress towards this project, which I have been working on with Alex Stringer here at Waterloo this term through the International Visiting Graduate Student program."
```

**Title**:
```{r echo=FALSE, results='asis'}
cat(title)
```

Title word count: `r stringr::str_count(title, '\\w+')`.

**Abstract**:
```{r echo=FALSE, results='asis'}
cat(abstract)
```

Abstract word count: `r stringr::str_count(abstract, '\\w+')`/200.
