---
title: "Point estimates comparison for the simplified Naomi model"
author:
- name: Adam Howes
output:
  bookdown::html_document2:
    toc: yes
    toc_float: yes
    toc_collapsed: yes
    df_print: paged
    code_folding: show
    theme: lumen
abstract: |
  **Background**  We have run the simplified Naomi model using a range of inference methods: `TMB`, `aghq`, and `tmbstan`.
  
  **Task** In this report, we compare the accuracy of the posterior distributions obtained from these inference methods using point estimates.
---

# Background

We compare the inference results from `TMB`, `aghq`, and `tmbstan`.
Import these inference results as follows:

```{r}
tmb <- readRDS("depends/tmb.rds")
aghq <- readRDS("depends/aghq.rds")
tmbstan <- readRDS("depends/tmbstan.rds")
```

# Means and standard deviations

```{r}
latent_pars <- unique(names(tmb$fit$par.full))[!(unique(names(tmb$fit$par.full)) %in% names(tmb$fit$par))]
output_pars <- c("rho_t1_out", "lambda_t1_out", "alpha_t1_out")        

type_key <- data.frame(
  par = c(latent_pars, output_pars),
  type = c(rep("latent", times = length(latent_pars)), rep("output", times = length(output_pars)))
)

df_tmb <- lapply(tmb$fit$sample[type_key$par], function(row) {
  data.frame("sd" = matrixStats::rowSds(row), "mean" = rowMeans(row)) %>%
    tibble::rowid_to_column("id")
  }) %>%
  dplyr::bind_rows(.id = "par") %>%
  mutate(method = "TMB")

df_aghq <- lapply(aghq$quad$sample[type_key$par], function(row) {
  data.frame("sd" = matrixStats::rowSds(row), "mean" = rowMeans(row)) %>%
    tibble::rowid_to_column("id")
  }) %>%
  dplyr::bind_rows(.id = "par") %>%
  mutate(method = "PCA-AGHQ")

df_tmbstan <- lapply(tmbstan$mcmc$sample[type_key$par], function(row) {
  data.frame("sd" = matrixStats::rowSds(row), "mean" = rowMeans(row)) %>%
    tibble::rowid_to_column("id")
  }) %>%
  dplyr::bind_rows(.id = "par") %>%
  mutate(method = "NUTS")

df <- bind_rows(df_tmb, df_aghq, df_tmbstan) %>%
  left_join(
    type_key,
    by = "par"
  )

df_plot <- df %>%
  pivot_longer(cols = c("sd", "mean"), names_to = "indicator", values_to = "estimate") %>%
  pivot_wider(values_from = "estimate", names_from = "method") %>%
  pivot_longer(cols = c("TMB", "PCA-AGHQ"), names_to = "method", values_to = "approximate") %>%
  rename("truth" = "NUTS") %>%
  mutate(
    indicator = fct_recode(indicator, "Posterior mean estimate" = "mean", "Posterior SD estimate" = "sd"),
    method = fct_relevel(method, "TMB", "PCA-AGHQ")
  )

df_metrics <- df_plot %>%
  group_by(method, indicator) %>%
  summarise(
    rmse = sqrt(mean((truth - approximate)^2)),
    mae = mean(abs(truth - approximate))
  )

df_metrics_pct <- df_metrics %>%
  ungroup() %>%
  group_by(indicator) %>%
  summarise(
    rmse_diff = 100 * diff(rmse) / max(rmse),
    mae_diff = 100 * diff(mae) / max(mae)
  )

df_metrics <- df_metrics %>%
  mutate(
    label = ifelse(
      method == "PCA-AGHQ",
      paste0("RMSE: ", round(rmse, 2), " (", round(df_metrics_pct$rmse_diff), "%)", "\nMAE: ", round(mae, 2), " (", round(df_metrics_pct$mae_diff), "%)"),
      paste0("RMSE: ", round(rmse, 2), "\nMAE: ", round(mae, 2))
    )
  )

write_csv(df_metrics, "mean-sd.csv")

mean_sd_plot <- ggplot(df_plot, aes(x = truth, y = approximate - truth)) +
  geom_point(shape = 1, alpha = 0.4) +
  facet_grid(indicator ~ method) +
  geom_abline(slope = 0, intercept = 0, linetype = "dashed") +
  geom_text(data = df_metrics, aes(x = -Inf, y = Inf, label = label), size = 3, hjust = 0, vjust = 1.5) +
  labs(x = "NUTS", y = "Approximation - NUTS") +
  theme_minimal()

ggsave("mean-sd.png", mean_sd_plot, h = 6, w = 6.25)

#' Split into two plots for presentations etc.

jitter_amount <- 0.02

mean_plot <- df_plot %>%
  filter(indicator == "Posterior mean estimate") %>%
  ggplot(aes(x = truth, y = approximate - truth)) +
  geom_jitter(shape = 1, alpha = 0.4, width = jitter_amount, height = jitter_amount) +
  lims(y = c(-0.4, 0.4)) +
  facet_grid(indicator ~ method) +
  geom_abline(slope = 0, intercept = 0, linetype = "dashed", size = 0.25) +
  geom_text(
    data = filter(df_metrics, indicator == "Posterior mean estimate"),
    aes(x = -Inf, y = Inf, label = label), size = 3, hjust = 0, vjust = 1.5
  ) +
  labs(x = "NUTS", y = "Approximation - NUTS") +
  theme_minimal()

ggsave("mean.png", mean_plot, h = 4, w = 6.25)

sd_plot <- df_plot %>%
  filter(indicator == "Posterior SD estimate") %>%
  ggplot(aes(x = truth, y = approximate - truth)) +
  geom_jitter(shape = 1, alpha = 0.4, width = jitter_amount, height = jitter_amount) +
  lims(y = c(-0.6, 0.6)) +
  facet_grid(indicator ~ method) +
  geom_abline(slope = 0, intercept = 0, linetype = "dashed", size = 0.25) +
  geom_text(
    data = filter(df_metrics, indicator == "Posterior SD estimate"),
    aes(x = -Inf, y = Inf, label = label), size = 3, hjust = 0, vjust = 1.5
  ) +
  labs(x = "NUTS", y = "Approximation - NUTS") +
  theme_minimal()

ggsave("sd.png", sd_plot, h = 4, w = 6.25)

sd_plot_alt <- sd_plot +
  theme(
    strip.background = element_blank(),
    strip.text.x = element_blank()
  )

y_axis <- ggplot(data.frame(l = mean_plot$labels$y, x = 1, y = 1)) +
  geom_text(aes(x, y, label = l), angle = 90) +
  theme_void() +
  coord_cartesian(clip = "off")

mean_plot_alt <- mean_plot
mean_plot_alt$labels$x <- ""
mean_plot_alt$labels$y <- sd_plot_alt$labels$y <- ""

mean_sd_plot_alt <- y_axis + (mean_plot_alt / sd_plot_alt) +
  plot_layout(widths = c(1, 30))

ggsave("mean-sd-alt.png", mean_sd_plot_alt, h = 6, w = 6.25)
```

# Original computing environment {-}

```{r}
sessionInfo()
```

# Bibliography {-}
